<?php
	define ("_home", "Upphafssíða");
	define ("_about", "Um vefinn");
	define ("_logbyli", "Lögbýli");
	define ("_preferences", "Stillingar");
	define ("_value", "Gildi");
	define ("_change", "Breyta");
	define ("_austurland", "Austurland");
	define ("_hofudborgar", "Höfuðborgarsvæðið");
	define ("_nordurland", "Norðurland");
	define ("_sudurland", "Suðurland og Reykjanes");
	define ("_vesturland", "Vesturland og Vestfirðir");
	define ("_pickarea", "Veldu landshluta að ofan");
	define ("_yes", "Já");
	define ("_no", "Nei");
	define ("_name", "Nafn");
	define ("_postcode", "Póstnr.");
	define ("_location", "Staðsetning");
	define ("_mapped", "Á korti");
	define ("_roads", "Vegakerfi");
	define ("_buildings", "Byggingar");
	define ("_imagery", "Á loftmynd");
	define ("_last_changed", "Síðast breytt");
	define ("_last_changed_by", "af");
	define ("_count", "Fjöldi");
	define ("_reset_filters", "endurstilla síur");
	define ("_unknown", "Óþekkt");
	define ("_login", "Innskráning með OSM");
	define ("_logout", "Útskráning");
	define ("_comments", "Athugasemdir");
	define ("_errorupdating", "Villa kom upp! Reyndu aftur.");
	define ("_viewOSM", "Skoða á OSM");
	define ("_editOSM", "Breyta á OSM");
	define ("_editID", "Breyta með iD");
	define ("_editJOSM", "JOSM");
	define ("_useJOSM", "Nota JOSM");
	define ("_dontuseJOSM", "Ekki nota JOSM");
	define ("_aboutJOSM", "<a href='http://josm.openstreetmap.de/'>JOSM</a> er kortaritill skrifaður í Java sem keyrir á þinni tölvu. Aðallega fyrir mjög reynda notendur. Til að geta opnað tengla hér í JOSM þarftu að hafa kveikt á <a href='http://josm.openstreetmap.de/wiki/Help/Preferences/RemoteControl'>Remote Control</a>.");
?>
