<?php
define ("_about", "About");
define ("_aboutJOSM", "<a href='http://josm.openstreetmap.de/'>JOSM</a> is a Java-based editor that runs on your computer. Reccomended for advanced users only. To be able to open JOSM links you need to have JOSM running on your computer with <a href='http://josm.openstreetmap.de/wiki/Help/Preferences/RemoteControl'>Remote Control</a> enabled.");
define ("_addresses", "Addresses");
define ("_amenities", "Amenities");
define ("_austurland", "East");
define ("_buildings", "Buildings");
define ("_change", "Change");
define ("_comments", "Comments");
define ("_count", "Count");
define ("_district", "Region");
define ("_dontuseJOSM", "Don't use JOSM");
define ("_editID", "Edit with iD");
define ("_editJOSM", "JOSM");
define ("_editOSM", "Edit OSM");
define ("_errorupdating", "An error occurred! Are you still logged in?");
define ("_hofudborgar", "Capital region");
define ("_home", "Home");
define ("_imagery", "Imagery");
define ("_last_changed", "Last changed");
define ("_last_changed_by", "by");
define ("_location", "Location");
define ("_logbyli", "Farms/estates");
define ("_login", "Login with OSM");
define ("_logout", "Logout");
define ("_mapped", "On map");
define ("_name", "Name");
define ("_no", "No");
define ("_nordurland", "North");
define ("_pickarea", "Choose a colored area above");
define ("_postcode", "Postal code");
define ("_preferences", "Preferences");
define ("_reset_filters", "reset filters");
define ("_streets", "Streets");
define ("_subdistrict", "Subregion");
define ("_sudurland", "South");
define ("_unknown", "Unknown");
define ("_useJOSM", "Use JOSM");
define ("_value", "Value");
define ("_vesturland", "West");
define ("_viewOSM", "View on OSM");
define ("_yes", "Yes");        
define ("_settlements", "Settlements");
define ("_network", "Network");
define ("_paths", "Paths");
define ("_mapillary", "Mapillary");
define ("_placetype", "Place");
?>